services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    container_name: proxy
    volumes:
      - ./proxy.py:/app/main.py
    ports:
      - 5555:5555
      - 5556:5556

  publisher_hora:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./publisher_hora.py:/app/main.py
    depends_on:
      - proxy

  publisher_dado:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./publisher_dado.py:/app/main.py
    depends_on:
      - proxy

  subscriber_hora:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./subscriber_hora.py:/app/main.py
    depends_on:
      - proxy

  subscriber_dado:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./subscriber_dado.py:/app/main.py
    depends_on:
      - proxy

  subscriber_todos:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./subscriber_todos.py:/app/main.py
    depends_on:
      - proxy
